### ISSUE TITLE
Building u-boot

### ISSUE THREAD

**Issue by zeilsteen2** [TobleMiner/u-boot-ralink#1]
Hello, thanks for the great M33 WRT version. But I can't build the u-boot for it. Or I don't understand how to using the readme.

Because I can only boot from net at the moment ( I flashed the upgrade bin using web interface of the wrt and changed the jumers but the web flasher in wrt does not flash u-boot I guess.

I did  a git clone https://github.com/TobleMiner/u-boot-ralink/
I have added the bin directory to paths with:
PATH=$PATH:/media/zeilsteen/compilespace/ledeM33/openwrt/bin
cd MikroTik-RBM33G

I created an sh file with:
export BUILD_TOPDIR=$(pwd) export STAGING_DIR=$BUILD_TOPDIR/tmp

make CROSS_COMPILE=mipsel-openwrt-linux-

head -c 196608 /dev/zero | tr '\000' '\377' > pwd | xargs basename.bin dd conv=$

Run it and get:

make[1]: Nothing to be done for `.depend'.
make[1]: Leaving directory `/media/zeilsteen/compilespace/ledeM33/openwrt/uboot/u-boot-ralink/MikroTik-RBM33G/tools'
make -C tools all
make[1]: Entering directory `/media/zeilsteen/compilespace/ledeM33/openwrt/uboot/u-boot-ralink/MikroTik-RBM33G/tools'
gcc -I./ -DUSE_HOSTCC -c mkimage.c
In file included from mkimage.c:61:0:
./image.h:27:25: fatal error: ../autoconf.h: No such file or directory
compilation terminated.
make[1]: *** [mkimage.o] Error 1
make[1]: Leaving directory `/media/zeilsteen/compilespace/ledeM33/openwrt/uboot/u-boot-ralink/MikroTik-RBM33G/tools'
make: *** [tools] Error 2
zeilsteen@zeilsteen-VirtualBox:/media/zeilsteen/compilespace/ledeM33/openwrt/uboot/u-boot-ralink/MikroTik-RBM33G$ nano ./uboot.sh
Use "fg" to return to nano.

[4]+  Stopped                 nano ./uboot.sh
zeilsteen@zeilsteen-VirtualBox:/media/zeilsteen/compilespace/ledeM33/openwrt/uboot/u-boot-ralink/MikroTik-RBM33G$ 

I think I'm overlooking something here. But i'm not an expert u-boot builder. Thanks!

As I read some more the updated openwrt should make a bin file that will boot with the normal mikrotik boatloader so maybe I'm trying something that is not needed.

**Comment by TobleMiner** [comment]
You do not need to buid U-boot for the rbm33g anymore. As of yesterday the openwrt images will simply boot with RouterBOOT. Just checkout the latest version of my development tree and build it. Updated instruction are here: https://github.com/openwrt/openwrt/pull/925

In case you do want to proceed with your old build and u-boot I think what you need to do is  run ```make menuconfig``` and just simply save the config once. That should generate the missing autoconf.h.

**Comment by zeilsteen2** [comment]
Thanks I will try the new version, at the moment the build keeps waiting on 

+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://mirror2.openwrt.org/sources/u-boot-2018.03.tar.bz2

+ curl -f --connect-timeout 20 --retry 5 --location --insecure ftp://ftp.denx.de/pub/u-boot/u-boot-2018.03.tar.bz2

Waits for more than 10 minutes. Will try again today. 

update: I think my build drive was full will try it again.

Thanks

Herman

**Comment by zeilsteen2** [comment]
It's working! Fantastic. Amazing job you got the board working with wrt. It now boots correctly into wrt after the Mikrotik bootloader without u-boot :) 👍

**Comment by TobleMiner** [comment]
@zeilsteen2 Nice, thanks for confirming!

**Comment by zeilsteen2** [comment]
No thanks, do you think it is hard to make the M11 board work? Only thing is it has 1 ethernet port and no serial port but I think allmost the same hardware only smaller. (same soc)
https://wikidevi.com/wiki/MikroTik_RouterBOARD_M11_(RBM11G)

I thought I'd give all ethernet ports an IP on the m33 and flash that rom directly to the m11 winbond chip. Do you think that has any chance? Problem is the board has no serial to give commands.

**Comment by TobleMiner** [comment]
@zeilsteen2 That board looks very similiar indeed. There are two unpopuated 2x5 pin headers on the board. Chances are there is a serial port on one of those. The serial port might be disabled though since it is normally not used.
The only major difference I can spot is the flash layout. The 11G seems to use a single flash chip only. On all the pictures of the board I can find there is an unpopulated SOIC-8 footprint on the flipside of the board. If your board has not got two flash chips the 33G image will not work without some modifications (see below for details).
Another (minor) thing that could be different between the 33G and the 11G are probably the GPIOs for controlling the reset button, the LEDs and PCIe power.

I think you should back up the flash on the 11G and take a look at where the RouterOS image starts. Normally that's pretty easy to do using binwalk:
![binwalk screenshot](https://user-images.githubusercontent.com/2042858/41769662-5bb713a0-7610-11e8-9338-1a8939d6c34e.png)

With mikrotik MIPS images the offset where the first YAFFS starts is generally the start of the RouterOS image. If that's the same on your device you could almost copy the part after 0x40000 from the 33G image. The only thing you might have to change is the chip select pin. It is very possible that the 11G connects its only flash chip to CS0. Thus you might have to change

```
	w25q128@0 {
		#address-cells = <1>;
		#size-cells = <1>;
		compatible = "jedec,spi-nor";
		reg = <1>;
		spi-max-frequency = <3125000>;

		partition@40000 {
			label = "firmware";
			reg = <0x040000 0xFC0000>;
		};
	};
```
to

```
	w25q128@0 {
		#address-cells = <1>;
		#size-cells = <1>;
		compatible = "jedec,spi-nor";
		reg = <0>;
		spi-max-frequency = <3125000>;

		partition@40000 {
			label = "firmware";
			reg = <0x040000 0xFC0000>;
		};
	};
```

in `target/linux/ramips/dts/RBM33G.dts`. But that's only speculation. You'll have to try that for yourself.

**Comment by TobleMiner** [comment]
Another thing I should probably mention is that the flash can only be read/written to when the MT7621 is held in reset state. To do so one of the pins on the header in the middle of the board must be pulled to ground. It's most likely one of the following pins:
![reset pins?](https://user-images.githubusercontent.com/2042858/41770842-a153425a-7613-11e8-9a16-da2d2d3fe27e.png)

Just try pulling them to ground using a 100 Ohm-ish resistor (up to 270 Ohm is probably fine, I had some problems using 680 Ohms though). My money is on pin 6 due to the circuitry attached to it.

**Comment by zeilsteen2** [comment]
Great I will try it, I'm now a little stuck at the IP command, because the openwrt build uses busybox and that version of IP does not work with tunnels. The command ip tunnel add ...etc  does not work. I installed the ip-full package as a package using the internet but I would like to build it directly in the image. Do you know how I need to do that? 

I'm now building with different busybox options from the menuconfig

**Comment by zeilsteen2** [comment]
The kernel file is loaded using tftp/dhcp but I can't ping or ssh it. 

This is how the 16mb winbond image of the m11g looks like:
A bit different than the m33. 

![m11g_winbond](https://user-images.githubusercontent.com/14131142/41814011-206dc572-7742-11e8-93cc-703352375747.png)

**Comment by TobleMiner** [comment]
@zeilsteen2 Looks pretty promising though. That image will probably boot. Have you tried connectiong to it directly and pinging ff02::1%<interface>? If the interface is up you should see at least two responses for each echo request. One of them will be the board. You can try to ssh to that ipv6 address then.

Regarding your iproute2 issues: There may be both, a busybox ip command and a ip binary at `/usr/bin/ip` try executing /usr/bin/ip, it might be different from ip.

**Comment by zeilsteen2** [comment]
@TobleMiner  This looks like OpenWrt:

156	367.515709	fe80::ce2d:e0ff:fe48:fe35	ff02::1:2	DHCPv6	168	Solicit XID: 0x5da364 CID: 00030001cc2de048fe35 
client fqdn: OpenWrt

But putty gives an connection refused on windows.

**Comment by TobleMiner** [comment]
@zeilsteen2 Ah, ok. I think you are connected to the WAN interface. By default OpenWrt rejects all connections via WAN port. I guess you could just rewrite the switch definition in `target/linux/ramips/base-files/etc/board.d/02_network`.
Replacing
`"1:lan" "2:lan" "3:lan" "4:lan" "0:wan" "6@eth0"`
with
`"1:wan" "2:lan" "3:lan" "4:lan" "0:lan" "6@eth0"` 
should work

**Comment by zeilsteen2** [comment]
Man you have great skills for this stuff. That worked! It is now netbooting and I'm now trying to make it permanent but my routerboot is on network only so I will have to install mikrotik first to change it.
But this is really great. Thanks a whole lot! Can I send you a PM?

**Comment by TobleMiner** [comment]
@zeilsteen2 Glad it helped. Sure, feel free to contact me :)

**Comment by zeilsteen2** [comment]
Great, the PM option is gone from git, whats your email mine is zeilsteen(a)gmail.com if you in the case you don't want it online.

**Comment by TobleMiner** [comment]
@zeilsteen2 Ah, sorry. Should have mentioned that before. You can contact me at tobleminer@gmail.com
